[package]
name = "jpdict"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2          = "1.1.4"
quick-xml       = "0.38.3"
rusqlite       = { version = "0.37.0", features = ["bundled"] }
ureq            = "3.1.2"